services:
  - type: static
    name: phstatic
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_ADMIN_PASSWORD_HASH
        sync: false
      - key: VITE_GOOGLE_ANALYTICS_ID
        sync: false
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_FORMSPREE_ID
        sync: false
      - key: VITE_WHATSAPP_NUMBER
        sync: false
